"""Type stubs for fasttag"""
from typing import Any, overload, Union

class HTML:
    """HTML string type"""
    def __init__(self, data: Union[str, bytes]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __add__(self, other: HTML) -> HTML: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __call__(self, *args: Any, **kwargs: Any) -> HTML: ...
    def bytes(self) -> bytes: ...
    def __html__(self) -> str: ...
    @property
    def tag(self) -> str: ...
    @property
    def attrs(self) -> dict[str, Any]: ...

DOCTYPE: HTML

def Text(text: str) -> HTML: ...
def tag(tag_name: str, *args: Any, **kwargs: Any) -> HTML: ...
def set_indent(indent: int) -> None: ...


# All HTML tag functions
# These accept content as positional args and attributes as keyword args
# Special keyword arguments:
#   - cls: CSS class (synonym for _class)
#   - _class: CSS class (converts to class attribute)
#   - _: any attribute starting with _ has the _ stripped
#   - other keywords: underscores are converted to hyphens

@overload
def A(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Abbr(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Address(*args: Any, **kwargs: Any) -> HTML: ...

def Area(**kwargs: Any) -> HTML: ...

@overload
def Article(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Aside(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Audio(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def B(*args: Any, **kwargs: Any) -> HTML: ...

def Base(**kwargs: Any) -> HTML: ...

@overload
def Bdi(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Bdo(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Blockquote(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Body(*args: Any, **kwargs: Any) -> HTML: ...

def Br(**kwargs: Any) -> HTML: ...

@overload
def Button(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Canvas(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Caption(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Cite(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Code(*args: Any, **kwargs: Any) -> HTML: ...

def Col(**kwargs: Any) -> HTML: ...

@overload
def Colgroup(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Data(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Datalist(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dd(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Del(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Details(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dfn(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dialog(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Div(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dl(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dt(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Em(*args: Any, **kwargs: Any) -> HTML: ...

def Embed(**kwargs: Any) -> HTML: ...

@overload
def Fieldset(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Figcaption(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Figure(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Footer(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Form(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H1(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H2(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H3(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H4(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H5(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def H6(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Head(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Header(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Hgroup(*args: Any, **kwargs: Any) -> HTML: ...

def Hr(**kwargs: Any) -> HTML: ...

@overload
def Html(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def I(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Iframe(*args: Any, **kwargs: Any) -> HTML: ...

def Img(**kwargs: Any) -> HTML: ...

def Input(**kwargs: Any) -> HTML: ...

@overload
def Ins(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Kbd(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Label(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Legend(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Li(*args: Any, **kwargs: Any) -> HTML: ...

def Link(**kwargs: Any) -> HTML: ...

@overload
def Main(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Map(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Mark(*args: Any, **kwargs: Any) -> HTML: ...

def Meta(**kwargs: Any) -> HTML: ...

@overload
def Meter(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Nav(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Noscript(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Object(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Ol(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Optgroup(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Option(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Output(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def P(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Param(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Picture(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Pre(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Progress(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Q(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Rp(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Rt(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Ruby(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def S(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Samp(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Script(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Section(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Select(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Small(*args: Any, **kwargs: Any) -> HTML: ...

def Source(**kwargs: Any) -> HTML: ...

@overload
def Span(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Strong(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Style(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Sub(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Summary(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Sup(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Table(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Tbody(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Td(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Template(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Textarea(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Tfoot(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Th(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Thead(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Time(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Title(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Tr(*args: Any, **kwargs: Any) -> HTML: ...

def Track(**kwargs: Any) -> HTML: ...

@overload
def U(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Ul(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Var(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Video(*args: Any, **kwargs: Any) -> HTML: ...

def Wbr(**kwargs: Any) -> HTML: ...

# Deprecated tags
@overload
def Acronym(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Applet(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Basefont(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Bgsound(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Big(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Blink(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Center(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Content(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Dir(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Element(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Font(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Frame(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Frameset(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Image(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Isindex(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Keygen(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Listing(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Marquee(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Menu(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Menuitem(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Multicol(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Nextid(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Nobr(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Noembed(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Noframes(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Plaintext(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Shadow(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Spacer(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Strike(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Tt(*args: Any, **kwargs: Any) -> HTML: ...

@overload
def Xmp(*args: Any, **kwargs: Any) -> HTML: ...

# SVG element tags
# Attribute convention: __ (double underscore) → : (colon) for namespace prefixes
#   e.g. xlink__href="..." → xlink:href="..."
#        xmlns__xlink="..." → xmlns:xlink="..."

def Svg(*args: Any, **kwargs: Any) -> HTML: ...
def Circle(*args: Any, **kwargs: Any) -> HTML: ...
def Ellipse(*args: Any, **kwargs: Any) -> HTML: ...
def Line(*args: Any, **kwargs: Any) -> HTML: ...
def Path(*args: Any, **kwargs: Any) -> HTML: ...
def Polygon(*args: Any, **kwargs: Any) -> HTML: ...
def Polyline(*args: Any, **kwargs: Any) -> HTML: ...
def Rect(*args: Any, **kwargs: Any) -> HTML: ...
def G(*args: Any, **kwargs: Any) -> HTML: ...
def Defs(*args: Any, **kwargs: Any) -> HTML: ...
def Symbol(*args: Any, **kwargs: Any) -> HTML: ...
def Use(*args: Any, **kwargs: Any) -> HTML: ...
def SvgText(*args: Any, **kwargs: Any) -> HTML: ...
def Tspan(*args: Any, **kwargs: Any) -> HTML: ...
def Stop(*args: Any, **kwargs: Any) -> HTML: ...
def Marker(*args: Any, **kwargs: Any) -> HTML: ...
def Pattern(*args: Any, **kwargs: Any) -> HTML: ...
def LinearGradient(*args: Any, **kwargs: Any) -> HTML: ...
def RadialGradient(*args: Any, **kwargs: Any) -> HTML: ...
def ClipPath(*args: Any, **kwargs: Any) -> HTML: ...
def Mask(*args: Any, **kwargs: Any) -> HTML: ...
def Filter(*args: Any, **kwargs: Any) -> HTML: ...
def ForeignObject(*args: Any, **kwargs: Any) -> HTML: ...
def View(*args: Any, **kwargs: Any) -> HTML: ...
def Animate(*args: Any, **kwargs: Any) -> HTML: ...
def AnimateMotion(*args: Any, **kwargs: Any) -> HTML: ...
def AnimateTransform(*args: Any, **kwargs: Any) -> HTML: ...
def Mpath(*args: Any, **kwargs: Any) -> HTML: ...
def FeBlend(*args: Any, **kwargs: Any) -> HTML: ...
def FeColorMatrix(*args: Any, **kwargs: Any) -> HTML: ...
def FeComponentTransfer(*args: Any, **kwargs: Any) -> HTML: ...
def FeComposite(*args: Any, **kwargs: Any) -> HTML: ...
def FeConvolveMatrix(*args: Any, **kwargs: Any) -> HTML: ...
def FeDiffuseLighting(*args: Any, **kwargs: Any) -> HTML: ...
def FeDisplacementMap(*args: Any, **kwargs: Any) -> HTML: ...
def FeDropShadow(*args: Any, **kwargs: Any) -> HTML: ...
def FeFlood(*args: Any, **kwargs: Any) -> HTML: ...
def FeFuncA(*args: Any, **kwargs: Any) -> HTML: ...
def FeFuncB(*args: Any, **kwargs: Any) -> HTML: ...
def FeFuncG(*args: Any, **kwargs: Any) -> HTML: ...
def FeFuncR(*args: Any, **kwargs: Any) -> HTML: ...
def FeGaussianBlur(*args: Any, **kwargs: Any) -> HTML: ...
def FeImage(*args: Any, **kwargs: Any) -> HTML: ...
def FeMerge(*args: Any, **kwargs: Any) -> HTML: ...
def FeMergeNode(*args: Any, **kwargs: Any) -> HTML: ...
def FeMorphology(*args: Any, **kwargs: Any) -> HTML: ...
def FeOffset(*args: Any, **kwargs: Any) -> HTML: ...
def FePointLight(*args: Any, **kwargs: Any) -> HTML: ...
def FeSpecularLighting(*args: Any, **kwargs: Any) -> HTML: ...
def FeSpotLight(*args: Any, **kwargs: Any) -> HTML: ...
def FeTile(*args: Any, **kwargs: Any) -> HTML: ...
def FeTurbulence(*args: Any, **kwargs: Any) -> HTML: ...
